# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 742812b01259c20cc5c057b430dff0a62762bf6f62d5784904ecd85e5474bb392930da06e885362ecb9a6095d740ce9f93d9c5da4425946b4ad77971a1862666

test:
  secret_key_base: 4eea70479ebc50bbfd41884e6d461cad6934f9441c16ac68d88ce3155b7c5c080132ce73da2f37f272c26a09326617c8b16dd754727da94db0acd4511989da21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
